blank_issues_enabled: false
contact_links:
  - name: Upstream Steam Audio documentation
    url: https://valvesoftware.github.io/steam-audio/
    about: Questions about how Steam Audio itself is supposed to behave.
